version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: automation-api-service
    ports:
      - "3032:3000"
    env_file:
      - .env
    restart: always